### ISSUE TITLE
Implement Default Tangram Gestures in iOS SDK

### ISSUE THREAD

**Issue by bleege** [mapzen/ios#131]
The SampleApp should implement the gesture recongizers defined in `TGRecognizerDelegate` to support basic interactions with the map.

/cc @ecgreb @msmollin

**Comment by bleege** [comment]
After building [a simple app](https://github.com/bleege/MapzenAndroidApp) using the latest Mapzen Android SDK (v1.2), it's now more clear that this issue actually is about implementing Pan, Pinch, Rotate, and Shove from Tangram in the iOS SDK's central map object.  This means by default _any app_ implementing the Mapzen iOS SDK will have it's map respond in a germane manner to these gestures.  Will use Android's [`MapzenMap.java`](https://github.com/mapzen/android/blob/765ef7860d1d4569b96c43792ad1c3202d95d360/core/src/main/java/com/mapzen/android/graphics/MapzenMap.java) as a guide.

**Comment by msmollin** [comment]
Hi Brad! Thanks for taking a look at this.

So the interplay between the Tangram-es iOS SDK and the Mapzen iOS SDK is definitely a little nebulous at the moment. Sorry about that. Let me offer a little insight.

There is a `MapViewController` object located here: https://github.com/mapzen/ios/blob/master/src/MapViewController.swift which as you can see is a subclass of `TGMapViewController`. 

This is a slightly different structure from how the Android SDK exposes things. Whereas in Android, Tangram-es SDK components are wrapped and thus effectively hidden from the implementing developer, on iOS we're subclassing from TGMapViewController, and so exposes the entire TGMapViewController API natively to implementing developers. We felt this was more in line with how Apple's UIKit functions and will be easier to handle by implementing developers.

So, swinging over to Tangram-es repository, you can see here: https://github.com/tangrams/tangram-es/blob/master/ios/src/TGMapViewController.h#L53 that we have a fairly fleshed out API available for the gesture recognizer delegates, and follows a similar pattern to things like `UITableViewControllerDataSource` and `UITableViewDelegate` established patterns. The `shouldRecognize` protocol methods are for overriding the default functionality provided by the Tangram-es codebase (viewable here: https://github.com/tangrams/tangram-es/blob/master/ios/src/TGMapViewController.mm#L557) and the `didRecgonize` callbacks are for developers to receive notifications about when tangram-es successfully recognized a gesture, and took an action. Semi-obviously, if you return `false` inside any of the `shouldRecognize` delegate callbacks, you will then have to implement your own map handling for that gesture, and subsequently will not receive any `didRecognize` variants of the same gesture.

Coming back over to the implementation in the Mapzen SDK, you can see here: https://github.com/mapzen/ios/blob/master/src/MapViewController.swift#L86 and here: https://github.com/mapzen/ios/blob/master/src/MapViewController.swift#L152 that we're already subscribing and partially implementing this delegate from the TGMapViewController subsystem

Ok, so that's how the proverbial sausage is made. Now, back to your issue - how do you think we should approach exposing this customization to the implementing developer?

**Comment by bleege** [comment]
Hi Matt!  Thank you for the insight on how everything is tied together and for confirming that `MapViewController.swift` is indeed the primary map object for app implementing developers to work with on iOS.  I'd seen the wrapping on the Android side that you mentioned and originally took that to mean the Mapzen Android SDK API was purposely mirroring the [Google Maps Android API](https://developers.google.com/maps/documentation/android-api/map).  This had me thinking that Mapzen iOS SDK API might do similar and mirror the [Apple Maps MapKit API](https://developer.apple.com/reference/mapkit).  Anyway, I've now built out an example of this in a [dev branch on my fork](https://github.com/bleege/ios/commits/131-gestures) and things work exactly as you said.

As for how to expose this customization to implementing developers, I agree with you and think the way it is now with the `shouldRecognize` and `didRecognize` functions makes sense using the `MapViewController.swift` as the central map object because it is consistent with how UIKit works.  This will become more clear to implementing developers [via documentation and examples](https://mapzen.com/documentation/ios/) similar to the [Mapzen Android SDK](https://mapzen.com/documentation/android/).

Finally, now that I know that the `MapViewController.swift` is designed to be the primary map object for implementing developers to override, I am curious about how to best use it to support multiple map views simultaneously.   For example, many navigation UIs have a large map showing zoomed in location and immediate surrounding area while also having a smaller map zoomed out and overlaid to show general location context on the same screen.  I know it's possible to use [multiple UIViewControllers in a single screen](http://jacopretorius.net/2013/04/using-multiple-viewcontrollers-on-a-single-screen-in-ios.html), but it seems like something that most iOS developers don't do.  It also seems like it'd limit the ability to work with the map in Interface Builder.  Is there a way to work directly with the a Mapzen MapView object in this case?

**Comment by msmollin** [comment]
Brad,
  Indeed we are aiming to replicate much of the functionality provided by Apple's Mapkit API. However, we're also trying to be aware of the other fairly large player in this space, [Google Maps iOS SDK](https://developers.google.com/maps/documentation/ios-sdk/), and so we're still trying to find a good balance between the two. For example, Mapkit provides no "locate me button" concept, whereas google does, and so we built a version of that [recently](https://github.com/mapzen/ios/blob/master/src/MapViewController.swift#L48).

Anyway, to answer your question about multiple maps, that is a use case we haven't tested heavily on either major mobile platform. However, it does appear to work just fine. Take a look here at a quick test I put together:
https://github.com/msmollin/MultimapTest

I put those little tests together frequently because it helps lay down what pain points are still lingering for implementors. This one showcases both the "map on top of map" example you requested, and a how to do that using Interface Builder storyboards. The secret lies with using Container Views which allow you to embed multiple VCs inside a single VC. This also allows for a straightforward Autolayout implementation.

There are definetly some issues we would need to address there, as it seems tangram-es isn't correctly capturing all the touch events - my guess is there's a problem with the responder chain not forwarding events to the large map's gesture recognizers (cc @karimnaaji). 

As for whether or not most iOS developers do or don't do that, well, they may not realize they do it but the entire system is built around that concept :) It's also straightforward to do that same example in code, although adding constraints becomes a little interesting at the code level.

**Comment by ecgreb** [comment]
One additional note here is that even though we are using wrappers for `MapView` and `MapController` in the Android SDK the goal isn't to mirror the Google Maps API explicitly but rather to offer a similar experience when possible.

There are some fundamental differences between Tangram and Google Maps that would prevent 100% API mirroring like the fact that Tangram is stylesheet based and allows more control over style customization.

**Comment by bleege** [comment]
Very cool Matt!  Thanks for the insight and the demo app on this Multiple Map setup.  Thanks also to both you and Chuck for the background on the design goals for both the Mapzen iOS and Android SDKs.  I love learning about the Mapzen features that are different from Apple and Google.

Speaking of which, I should clarify more about where I was coming from [when I referred to mirroring MapKit above](https://github.com/mapzen/ios/issues/131#issuecomment-270023153) as I think the three of us are on the same page.  What I was thinking was to mirror the same MapKit API as a baseline / starting point for the Mapzen iOS SDK for features common to both platforms and then implement the Tangram / Mapzen specific features as new API in addition to this baseline.  This provides the "similar experience when possible" that Chuck mentioned which also in my experience I've found to be super helpful for apps / developers coming to a new map / geo SDK as many developers don't have a lot of experience with maps / geo.  It also makes it much easier for them to swap out Apple (on iOS) or Google (on Android) for Mapzen in their apps, get a quick win, and feel confident and willing to learn the "new to them" stuff.  This is especially true for developers who are just kicking the tires of the SDKs with their apps even before they feel confident in suggesting a new SDK to their colleagues / companies.

Anyway, I knew that the Mapzen iOS SDK is still very new and under very active development.  Based on my previous experience with [LOST](https://github.com/mapzen/LOST) and seeing the Mapzen Android SDK setup along this way with `MapView` and `MapController` I had it in my head that the Mapzen iOS SDK would likely be following suit.  It certainly doesn't have to and you definitely have good reasons to not.  That's just where I was initially coming from and my 2 cents.  😄

**Comment by ecgreb** [comment]
Thanks for the insights and feedback @bleege its always good to get a variety of perspectives.

I attribute much of the succes of Lost to reducing the friction for adoption by new developers and we're hoping to do the same here where possible.

Given that we are just coming up on our first alpha release on iOS the API is still very much subject to change and we're open to suggestions!

**Comment by msmollin** [comment]
What @ecgreb said. Anywhere you think improvement can be made or changed to more closely align with a particular API feel free to open an issue / PR.

**Comment by bleege** [comment]
Thanks @ecgreb @msmollin !  Will do.

As for this particular ticket it was originally for implementing gesture recognizers in the Sample App and SDK.  Thanks to [the overview from @msmollin above](https://github.com/mapzen/ios/issues/131#issuecomment-269427130), it's no longer an issue so it can be closed.
