### ISSUE TITLE
Implement NSBundle-approach to loading style sheets

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#159]
Even with the fix here: #158, implementing devs would need to use a scene line that looks like `loadScene("Frameworks/Mapzen_ios_sdk.framework/scenes/scene.yaml")`

So, the solution here is to implement something similar to what got implemented in the tangram iOS SDK - https://github.com/tangrams/tangram-es/blob/master/ios/src/platform_ios.mm#L73

This would ideally yield something that looks more like `loadScene("scene.yaml")` - but with a different function call to contain the extra logic specific to the mapzen-ios-sdk. 

The surrounding code may or may not be required as well to make sure the sample app inside the SDK repository works correctly.

**Comment by msmollin** [comment]
@karimnaaji / @matteblair any additional thoughts you may have on this?

**Comment by ecgreb** [comment]
Does this mean the sample app should be updated to load the scene in the way you describe above until a more comprehensive solution is implemented?

https://github.com/mapzen/ios/blob/master/SampleApp/TangramVC.swift#L15

**Comment by karimnaaji** [comment]
Agreed that this is not convenient at all, I don't see any reason why this wouldn't work at the SDK level. If you get handle to the SDK framework, and overload `loadScene` it would work. 

But more generally, I don't think that the user should be able to reference any internal SDK paths from the API side other than wrapped up under defines. It was a little different for Tangram since those resources were used as font fallbacks and not used from the API side.

If you want to load a scene, as in the style switcher in Android, the proper defines would that issue; since the user would only either load a scene by using this define name `loadScene(scenes.style_name)`, a remote URL, or a path to the client application.

**Comment by msmollin** [comment]
@ecgreb no the sample app will still work as currently writen because the SDK source code is included in the same module as the sample app code. The line I listed above is only necessary for implementing developers because the iOS SDK will be outside the implementing app's bundle. I only mentioned the sample app because once we add the logic that Tangram uses for this purpose, we will need to make sure to re-test the sample to make sure it isn't problem

@karimnaaji awesome and yeah totally agreed. The work on the style switcher will include an enumeration like you listed. There is still the outstanding question @tallytalwar brought up before about submodules vs cocoapods for the styles themselves. That is something we'll need to tackle as well as part of this.

**Comment by msmollin** [comment]
This was implemented as part of https://github.com/mapzen/ios/pull/272
