### ISSUE TITLE
Pinching should disable current location tracking

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/ios#173]
Currently only panning disables current location tracking but it feels like any change in the map's position/zoom/rotation should disable it

**Comment by matteblair** [comment]
I think the current behavior actually makes the most sense for a user experience. Panning the map pretty clearly indicates that we shouldn't keep tracking the current location, but pinching/zooming is less clear because changing zoom doesn't imply an intent to change the map's focus position. 

There's also the interaction with the "current location" button to consider. When someone activates the "current location" button, the map goes to our current location and to a specific zoom that we've pre-determined. Someone might want to track their current location, but at a different zoom level than the one that the button sets. If changing zoom disables current location tracking, then this becomes impossible.
