### ISSUE TITLE
Switching tabs in demo app breaks map?

### ISSUE THREAD

**Issue by ecgreb** [mapzen/ios#222]
Memory issue?
Find me button tends to quit first.
Switching to routing tab makes basic map demo tab turn black (sometimes).
`didReceiveMemoryWarning` should be better handled in Tangram

**Comment by msmollin** [comment]
Ultimately this is a memory issue. `TGMapViewController`, in low memory situations, destroys its `GLKView` which is not re-created easily. There's a 2 part approach to this:

1) Short term: We can intercept this at the SDK level and handle it more gracefully. I'll be putting a PR in for this.

2) Long term this really should get handled better in the underlying tangram-es codebase by not just destroying its `GLKView.` Ticket is here to track that work: https://github.com/tangrams/tangram-es/issues/1393

Ultimately we'll still have to handle some things in a low memory scenario but not at the level that the short term band-aid will fix.

**Comment by msmollin** [comment]
So, for the band-aid fix, what I plan on having happen (and what I have working):

1) Intercept `didReceiveMemoryWarning()` and handle the call before TGMapViewController gets notified (a bonus of having it as a child view controller).
2) Remove all constraints 
3) Gracefully remove the map controller from the view hiearchy and the view controller relationship.
4) Gather all state in a state tracker object (pan, tile, zoom, etc.)
5) Explicitly remove delegates to prevent extraneous callbacks while the system cleans up memory.
6) Remove our reference to the TGMapVC and recreate a fresh instance

Then, on `viewWillAppear()` (as it's the earliest re-entrant point)
1) Redo the TGMapVC initial state
2) Reload the scene async.

On completion of scene file load: 
1) Reload any annotations we had added, creating new markers and re-establishing that relationship
2) Reset the pan/tilt/zoom/etc. states
3) Recreate the attribution button
4) Recreate the find me button
5) Re-attach the delegates

Additionally we're going to need to track ourselves whether or not we're visible, since in certain scenarios (Scroll Views mostly) the system will return an incorrect value as you are off screen but still in the view hierarchy.

**Comment by msmollin** [comment]
Depends on #235 getting fixed as well so re-setting state works correctly.

**Comment by matteblair** [comment]
Sounds like life would be a lot simpler if tangram had its own handler for memory warnings that didn't completely trash the view hierarchy. We can schedule that for the next tangram-es release (ETA 1.5 weeks), would you want this fixed before that?

**Comment by karimnaaji** [comment]
I'm currently working on the fix relating to that on the tangram-es side. Which will go in the next release as @matteblair said.

**Comment by msmollin** [comment]
@matteblair I don't think we need to before the next release, and yeah agreed on improving tangram's behavior. However we're still going to need some of this in the SDK for things like re-creating route lines, and re-connecting markers to annotation objects, but it would be great not to have to redo constraints or reload the scene :)

**Comment by tallytalwar** [comment]
Yup exactly what we discussed in the standup today. Also mentioning https://github.com/tangrams/tangram-es/issues/1393 here.
