### ISSUE TITLE
Show direction of view along with current location

### ISSUE THREAD

**Issue by nvkelso** [mapzen/ios#333]
### Description

Right now we show the current location as a circle icon coming from basemap style. But that only shows "now" when I'm often interested in "where to". 

It'd be nice to have a new icon for "directional" current location that had a triangle icon that stuck off to the side, and the icon rotated so the triangle oriented towards the direction of view.

This is something fairly common with both Google and Apple already supporting this feature in their mapping apps.

**Comment by msmollin** [comment]
So basically this is just creating the standard "Compass" UI Component like we have in eraser map already?

**Comment by matteblair** [comment]
I understood this to be about displaying the orientation of the phone in the world, rather than displaying the orientation of the map on the phone (which is what the "compass" on the Android SDK does). I also think this would be super helpful! I don't know what additional work this would require from our "location provider" code, if any.

Rendering an approximate-view-cone similar to that on Google or Apple Maps should be possible with Tangram ES, but I'm not sure we'll be able to smoothly rotate it with orientation updates.

**Comment by msmollin** [comment]
Closing in favor of #391
